# Generated by Django 4.2.6 on 2023-10-20 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_alter_flight_options_alter_ticket_flight_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("flight", "row", "seat")},
        ),
    ]
