# Generated by Django 4.2.6 on 2023-10-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_alter_ticket_options_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(related_name="flight", to="airport.crew"),
        ),
    ]
