# Generated by Django 4.2.6 on 2023-11-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0005_alter_route_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.IntegerField(default=2000),
        ),
    ]
