# Generated by Django 4.2.6 on 2023-11-12 20:19

import airport.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0006_alter_route_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.utils.crew_image_file_path
            ),
        ),
    ]
